### PR TITLE
Update KDE runtime to 6.8

### PR DESCRIPTION
**Pull request by guihkx**

### CODE REVIEW

**Comment by nuttyartist** [comment]
I think we still got this issue unresolved: https://github.com/nuttyartist/notes/pull/714#issuecomment-2434350270

**Comment by guihkx** [comment]
>I think we still got this issue unresolved: https://github.com/nuttyartist/notes/pull/714#issuecomment-2434350270

Doesn't that only affect macOS, though?

In any case, I'll make sure to test it once the Flatbub bot creates a build.

I'm curious to see if this Qt update fixes the Wayland issue where we can't edit labels in the Kanban view (https://github.com/nuttyartist/notes/issues/617).

**Comment by guihkx** [comment]
@nuttyartist I don't think the issue you mentioned affects Linux:

image

The Wayland issue is still present though, so we can't enable the Wayland socket yet. :/

Still, I think we should merge this.

**Comment by nuttyartist** [comment]
> I don't think the issue you mentioned affects Linux:

Seems like it doesn't. Good.

> The Wayland issue is still present though, so we can't enable the Wayland socket yet

Which Wayland issue?

**Comment by guihkx** [comment]
This one: https://github.com/nuttyartist/notes/issues/617

**Review by zjeffer — APPROVED** [review]

**Review by nuttyartist — APPROVED** [review]

**Pull request merged**
